name: Docker
description: Runs your build steps in Docker containers
author: https://github.com/buildkite
requirements:
  - docker
configuration:
  properties:
    image:
      type: string
    workdir:
      type: string
    always-pull:
      type: string
    mount-buildkite-agent:
      type: boolean
    mounts:
      type: [boolean,array]
    volumes:
      type: [boolean,array]
    command:
      type: array
    entrypoint:
      type: string
    environment:
      type: array
    user:
      type: string
    additional_groups:
      type: array
    network:
      type: string
    debug:
      type: boolean
    runtime:
      type: string
    shell:
      type: [boolean, array]
  required:
    - image
  additionalProperties: false
