steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files: hooks/**

  - label: ":sparkles:"
    plugins:
      plugin-linter#v2.0.0:
        id: docker

  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v3.0.2:
        run: tests
