steps:
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**
            - commands/**
            - lib/**

  - label: ":sparkles:"
    plugins:
      - plugin-linter#v3.3.0:
          id: docker

  - label: ":docker: :hammer:"
    plugins:
      - plugin-tester#v1.2.0: ~

  - label: "Security Scan"
    key: security_scan
    plugins:
      - secrets#v1.0.0:
          variables:
            GITHUB_TOKEN: GITHUB_TOKEN
      - ossf-scorecard#v1.0.0:
          github_token: $$GITHUB_TOKEN

  - wait: ~

  - label: run the plugin
    command: "echo hello world"
    plugins:
      - ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
          image: ubuntu:22.04
  - label: ensure exit codes are propagated
    command: "exit 3"
    plugins:
      - ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
          image: ubuntu:22.04
    soft_fail:
      - exit_status: 3
