#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"

if [[ -n "${BUILDKITE_PLUGIN_DOCKER_LOAD:-}" ]]; then
  # shellcheck source=commands/load.sh
  . "$DIR/../commands/load.sh"
fi

# shellcheck source=commands/run.sh
. "$DIR/../commands/run.sh"