#!/bin/bash

set -euo pipefail

if [[ -n "${BUILDKITE_BIN:-}" ]] ; then
  BUILDKITE_BIN=$(which buildkite-agent)
fi

docker run \
  -it \
  --rm \
  -e BUILDKITE_JOB_ID \
  -e BUILDKITE_BUILD_ID \
  -e BUILDKITE_AGENT_ACCESS_TOKEN \
  -v "$BUILDKITE_BIN:/usr/bin/buildkite-agent" \
  -v "$(pwd):${BUILDKITE_PLUGIN_DOCKER_WORKDIR}" \
  --workdir "${BUILDKITE_PLUGIN_DOCKER_WORKDIR}" \
  "${BUILDKITE_PLUGIN_DOCKER_IMAGE}" \
  bash -c "${BUILDKITE_COMMAND}"
